# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# 

name: Node.js CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: 18
    - name: Wait on
      uses: iFaxity/wait-on-action@v1
      with:
        resource: ${{ vars.GATSBY_API_URL }}/actuator/health
        timeout: 300000
        interval: 5000
        verbose: true
    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
          browser: chrome
          start: yarn start
          wait-on: 'http://127.0.0.1:8000'
          wait-on-timeout: 150
      env: 
        API_KEY: ${{ secrets.API_KEY }}
        GATSBY_API_URL: ${{ vars.GATSBY_API_URL }}
